//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWorryWonder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPA_GR_Data
    {
        public System.DateTime Date { get; set; }
        public string Source { get; set; }
        public int Site_ID { get; set; }
        public int POC { get; set; }
        public decimal Daily_Max_8_hour_Ozone_Concentration { get; set; }
        public string UNITS { get; set; }
        public int DAILY_AQI_VALUE { get; set; }
        public string Site_Name { get; set; }
        public int DAILY_OBS_COUNT { get; set; }
        public int PERCENT_COMPLETE { get; set; }
        public int AQS_PARAMETER_CODE { get; set; }
        public string AQS_PARAMETER_DESC { get; set; }
        public int CBSA_CODE { get; set; }
        public string CBSA_NAME { get; set; }
        public int STATE_CODE { get; set; }
        public string STATE { get; set; }
        public int COUNTY_CODE { get; set; }
        public string COUNTY { get; set; }
        public double SITE_LATITUDE { get; set; }
        public double SITE_LONGITUDE { get; set; }
        public int Id { get; set; }
    }
}
