//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWorryWonder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPAGRDataFinal
    {
        public System.DateTime Date { get; set; }
        public double Daily_Max_8_hour_Ozone_Concentration { get; set; }
        public string UNITS { get; set; }
        public byte DAILY_AQI_VALUE { get; set; }
        public string Site_Name { get; set; }
        public double SITE_LATITUDE { get; set; }
        public double SITE_LONGITUDE { get; set; }
        public int id { get; set; }
    }
}
