//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWorryWonder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory_Pollutant_Final
    {
        public string Div_Id { get; set; }
        public string Location { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double EtO_ugm3 { get; set; }
    }
}
