//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWorryWonder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory_Pollution
    {
        public string Location { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public Nullable<decimal> ETO_ppm { get; set; }
        public Nullable<decimal> ETO_ppbv { get; set; }
        public decimal MDL_ppm { get; set; }
    }
}
