//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWorryWonder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ost_data_Jan_June2019
    {
        public string dev_id { get; set; }
        public string time { get; set; }
        public Nullable<decimal> o3 { get; set; }
        public Nullable<decimal> pm10Average { get; set; }
        public Nullable<decimal> pm1Average { get; set; }
        public Nullable<decimal> pm25 { get; set; }
        public Nullable<decimal> pm25Average { get; set; }
        public Nullable<decimal> pm25Count { get; set; }
        public Nullable<decimal> pm25Max { get; set; }
        public Nullable<decimal> pm25Min { get; set; }
        public Nullable<decimal> pmStatus { get; set; }
        public Nullable<decimal> port { get; set; }
        public Nullable<decimal> specHumid { get; set; }
        public Nullable<decimal> specO3Average { get; set; }
        public Nullable<decimal> specO3Count { get; set; }
        public Nullable<decimal> specO3max { get; set; }
        public Nullable<decimal> specO3min { get; set; }
        public Nullable<decimal> specStatus { get; set; }
        public Nullable<decimal> specTemp { get; set; }
        public int Id { get; set; }
    }
}
