//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWorryWonder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ost_Data_March_Final
    {
        public string dev_id { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
        public double o3 { get; set; }
        public double pm25 { get; set; }
        public double pm25Average { get; set; }
        public int id { get; set; }
    }
}
