//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWorryWonder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class simms_data_Jan_June2019
    {
        public string dev_id { get; set; }
        public string time { get; set; }
        public decimal co { get; set; }
        public decimal humdity { get; set; }
        public decimal no2 { get; set; }
        public decimal no2_o3 { get; set; }
        public decimal o3 { get; set; }
        public decimal pm25 { get; set; }
        public decimal so2 { get; set; }
        public decimal status { get; set; }
        public decimal temperature { get; set; }
        public decimal vin { get; set; }
        public int Id { get; set; }
    }
}
