//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWorryWonder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WWWEntities : DbContext
    {
        public WWWEntities()
            : base("name=WWWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EPAGRDataFinal> EPAGRDataFinals { get; set; }
        public virtual DbSet<simms_Data_Feb_Apr_Final> simms_Data_Feb_Apr_Final { get; set; }
        public virtual DbSet<Factory_Pollutant_Final> Factory_Pollutant_Finals { get; set; }
        public virtual DbSet<Ost_Data_March_Final> Ost_Data_March_Final { get; set; }
    }
}
