//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWorryWonder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherWorryWonderDBEntities : DbContext
    {
        public WeatherWorryWonderDBEntities()
            : base("name=WeatherWorryWonderDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EPA_GR_Data> EPA_GR_Data { get; set; }
        public virtual DbSet<ost_data_Jan_June2019> ost_data_Jan_June2019 { get; set; }
        public virtual DbSet<simms_data_Jan_June2019> simms_data_Jan_June2019 { get; set; }
        public virtual DbSet<Factory_Pollution> Factory_Pollution { get; set; }
    }
}
